/**
 * Ryno Pierce
 * 12003922
 * COS 301: Reporting B: exportThreadAppraisal
 * 21.03.2015
 */

/**
 * The functionality provided by the exportThreadAppraisal function is to provide a way to export a JSON object
 * ,created by the getThreadAppraisal function, to a csv file
 * @param threadObject - object generated by the getThreadAppraisal function
 * @param directory - The directory to store the file in
 * @param fileName - The name for the file. Must end in .csv for example Test.csv.
 */

module.exports = function(threadObject,directory,fileName){
    var fs = require('fs');
    var path = require('path');
    var filePath = path.join(directory,fileName);
    var parseToCsv = exportThreadAppraisal(threadObject);
    fs.writeFile(filePath, parseToCsv, function (err) {
        if (err) return console.log(err);
    });
};

    /** Function to convert a JSON object to a csv object string.
     *@param threadObject - the JSON object created by the getThreadAppraisal
     * */
function exportThreadAppraisal( threadObject)
{
    /** Turn JSON object into a SCV compatible string */
    var array = typeof threadObject != 'object' ? JSON.parse(threadObject) : threadObject;
    var strCSV = '';

    for (var i = 0; i < array.length; i++) {
        var line = '';
        for (var index in array[i]) {
            if (line != '') line += ','

            line += array[i][index];
        }

        strCSV += line + '\r\n';
    }
    /** Return the CSV compatible string.*/
    return strCSV;

    /** Save to CSV file - Doesn't work in node */
   /* var downloadLink = document.createElement("a");
    var blob = new Blob(["\ufeff", strCSV]);
    var url = URL.createObjectURL(blob);
    downloadLink.href = url;
    downloadLink.download = filename;

    document.body.appendChild(downloadLink);
    downloadLink.click();
    document.body.removeChild(downloadLink);*/
}

